platzigram/urls.py
# Modulo de URLs

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from platzigram import views as local_views
from posts import views as posts_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello-world/', local_views.hello_world, name='hello-world'),
    path('timers/', local_views.timers, name='timers'),
    path('sorted/', local_views.sort_integers, name='sorted'),
    path('hi/<str:name>/<int:age>/', local_views.say_hi, name='hi'),



    path('posts-test/', posts_views.list_posts_test),
    # Esto es para incluir las dos rutas de abajo en una en otro archivo
    path('', include( ('posts.urls', 'posts'), namespace='posts') ),
    # el / es innecesario por eso se deja en vacio
    # path('', posts_views.list_posts, name='feed'),
    # path('posts/new', posts_views.create_post, name='create_post'),

    # argumentos
    # 'users/' : init path
    # 'users.urls' : file where are the urls
    # 'users' : aplication -> la aplicacion
    # namespace : namespace de las urls 
    path('users/', include( ('users.urls', 'users'), namespace='users' ) ),
    # path('users/login/', users_views.login_view, name='login'),
    # path('users/logout/', users_views.logout_view, name='logout'),
    # path('users/signup/', users_views.signup_view, name='signup'),
    # path('users/me/profile', users_views.update_profile, name='update_profile'),


    # servir archivos staticos, imagenes
    # https://docs.djangoproject.com/en/3.1/ref/settings/
] + static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

posts/urls.py
from django.urls import path

from posts import views

urlpatterns = [
  path(
    route='', 
    # view= views.list_posts,
    view= views.PostFeedView.as_view(),
    name='feed'
  ),

  path(
    route='posts/new',
    # view=views.create_post,
    view= views.CreatePostView.as_view(),
    name='create'
  ),

  path(
    route='<int:id>',
    view=views.PostDetailView.as_view(),
    name='details'
  ),
]

users/urls.py
# Django
from django.urls import path
from django.views.generic import TemplateView

# Models
from users import views


urlpatterns = [

  # Management
  path(
    route= 'login/',
    # view= views.login_view, 
    view= views.LoginView.as_view(),
    name='login'
  ),

  path(
    route= 'logout/',
    # view= views.logout_view, 
    view= views.LogoutView.as_view(),
    name='logout'
  ),

  path(
    route= 'signup/',
    # view= views.signup_view, 
    view= views.Signup.as_view(),
    name='signup'
  ),
  path(

    route= 'me/profie', 
    # view= views.update_profile, 
    view= views.UpdateProfileView.as_view(),
    name='update'
  ),

  # Posts
  # https://docs.djangoproject.com/en/3.1/topics/class-based-views/
  path(
    route= "<str:username>/",
    # view= TemplateView.as_view(template_name='users/detail.html'),
    view= views.UserDetailView.as_view(),
    name="detail"
  ),

]

users/models.py
from django.db import models
# https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#extending-the-existing-user-model
from django.contrib.auth.models import User

# Create your models here.

'''
  Profile model Proxy model that extiends the base data with other infiormation
  extendiende de la clase User

  https://docs.djangoproject.com/en/3.1/ref/models/fields/#textfield
'''
class Profile(models.Model):

  # un perfil solo puede tener un usuario, y un usuario solo puede tener este perfil
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  website = models.URLField(max_length=200, blank=True)

  biography = models.TextField(blank=True)

  phone_number = models.CharField(max_length=20, blank=True)

  picture = models.ImageField(upload_to='users/pictures', blank=True, null=True )

  created = models.DateTimeField(auto_now_add=True)

  modified = models.DateTimeField(auto_now=True)

  # Esto es para la representacion del objecto para que no devuelva un Object en consola
  def __str__ (self):
    return self.user.username

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, FormView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

# exception
from django.db.utils import IntegrityError 

# Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

# https://docs.djangoproject.com/en/3.1/topics/forms/
# https://docs.djangoproject.com/en/3.1/ref/forms/fields/
# Forms 
from users.form import ProfileForm, SignupForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/#auth-web-requests
# Create your views here.
def login_view(request):
  # import pdb; pdb.set_trace()

  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
  
    user = authenticate( request, username=username, password=password )

    if user is not None:
      login(request, user)
      # feed es el nombre de la url del posts -> /
      return redirect('posts:feed')
    else:
      return render(request, 'users/login.html', {'error': 'Invalid username and password'})

  return render(request, 'users/login.html')

# https://docs.djangoproject.com/en/3.1/topics/auth/default/#module-django.contrib.auth.views
class LoginView( auth_views.LoginView ):
  '''Login view'''

  template_name = 'users/login.html'
  
  # al hacer success, esto redirecciona hacia http://localhost:8000/accounts/profile/
  # para cambiar esto, se va hacia platzigram/settings y añadir
  # LOGIN_REDIRECT_URL = '/ - settings.LOGIN_REDIRECT_URL





def signup_view(request):
  
  if request.method == 'POST':
    form = SignupForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('users:login')
  else:
    form = SignupForm()

  return render(
    request=request,
    template_name='users/signup.html',
    context={
      'form': form
    }
  )

# https://ccbv.co.uk/projects/Django/3.0/django.views.generic.edit/FormView/
# Reemplazar la funcion signup_view por una clase FormView
class Signup(FormView):
  '''Users sign up view'''
  
  template_name = 'users/signup.html'
  form_class = SignupForm
  success_url = reverse_lazy('users:login')

  def form_valid(self, form):
    '''Save for data.'''
    form.save()
    return super().form_valid(form)

# Esta es sin aplicarle el Form
# def signup_view(request):
#   if request.method == 'POST':
    
#     username = request.POST['username']
#     password = request.POST['password']
#     password_confirmation = request.POST['password_confirmation']
#     first_name = request.POST['first_name']
#     last_name = request.POST['last_name']
#     email = request.POST['email']

#     if password != password_confirmation:
#       return render(request, 'users/signup.html', {'error': 'Password confirmation does not mach'} )

#     try:
#       user = User.objects.create_user(username=username, password=password)  
#       # catch un error particularmente, lo obtuve de la consola
#     except IntegrityError:
#       return render(request, 'users/signup.html', {'error': 'Username is alredy in user'} )

#     user.first_name = first_name
#     user.last_name = last_name
#     user.email = email
#     user.save()

#     # Profile
#     profile = Profile(user=user)
#     profile.save()

#     return redirect('login')

#   return render(request, 'users/signup.html')

@login_required
def update_profile(request):
  '''Update a user's profile view.'''

  profile  = request.user.profile

  if request.method == 'POST':
    form = ProfileForm(request.POST, request.FILES)
    if form.is_valid():
      data = form.cleaned_data

      profile.website = data['website']
      profile.phone_number = data['phone_number']
      profile.biography = data['biography']
      profile.picture   = data['picture']
      profile.save()

      url = reverse('users:detail', kwargs={'username': request.user.username})
      return redirect(url)
  else: 
    form = ProfileForm()

  return render(
    request=request,
    template_name='users/update_profile.html',
    context={
      'profile': profile,
      'user': request.user,
      'form': form
    }
  )

# Actualizar formulario
# https://ccbv.co.uk/projects/Django/3.0/django.views.generic.edit/UpdateView/
class UpdateProfileView(LoginRequiredMixin, UpdateView):
  '''Update profile view.'''
  model = Profile
  template_name = "users/update_profile.html"
  # campos a editar
  fields = ['website', 'biography', 'phone_number', 'picture']

  def get_object(self):
    '''Return user's profile'''
    return self.request.user.profile
  
  def get_success_url(self):
    '''Return to user's profile'''
    username = self.object.user.username
    return reverse('users:detail', kwargs={'username': username} )



@login_required
def logout_view(request):
  logout(request)
  return redirect('users:login')



class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
  '''Logout view'''
  # ejemplo pero no hara nada, es el template del logout que no tiene
  template_name = 'users/logged_out.html'

  # setear la url al redirigir en settings.LOGOUT_REDIRECT_URL


# https://ccbv.co.uk/projects/Django/3.0/django.views.generic.detail/DetailView/
# https://docs.djangoproject.com/en/3.1/ref/class-based-views/generic-display/#detailview

# ya no es un TemplateView sino lo vamos a pasar a un detailView
# LoginRequiredMixmin proteger la vista
class UserDetailView( LoginRequiredMixin, DetailView ):

  template_name='users/detail.html'
  # el where de la data
  slug_field = 'username'
  # lo que viene en la url /username 
  slug_url_kwarg = 'username'
  # Donde buscar la data
  queryset = User.objects.all()
  # nombre del objeto que se le manda al template
  context_object_name = 'user'

  # agregar posts al usuario del context
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    user = self.get_object()
    context["posts"] = Post.objects.filter(user=user).order_by('-created')
    return context
  

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5"id="auth-container">
                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:details' post.id %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
  <title> Platzigrm sign in </title>
{% endblock head_content %}

{% block container %}

  {% comment %} como estoy usando formularion clase, el error ahora viene desde form
  how i'm using Class form, the error comes from Form {% endcomment %}
  {% if form.errors %}
    <p class="alert alert-danger">  {{ form.errors }} </p>
  {% endif %}
  

  {% comment %} login es el nombre de la url que le pusimos en urls.py {% endcomment %}
  <form method="POST" action="{% url 'users:login' %}">

    {% comment %} token input por session csrf_token, al hacer GET a esta pagina lo obtendre {% endcomment %}
    {% csrf_token %}

    <div class="form-group">
      <input type="text" placeholder="Username" name="username" class="form-control" />
    </div>

     <div class="form-group">
      <input type="password" placeholder="Password" name="password" class="form-control"  />
    </div>

    <button type="submit" class="btn btn-primary btn-block mt-5"> Sign In </button>
  </form>

  <p class="mt-4"> Don't have an account yet? <a href="{% url 'users:signup' %}"> Sign up here. </p>
{% endblock container %}

templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
  <title> Platzigram Signup </title>
{% endblock head_content %}

{% block container %}

  {% if error %}
    <p class="alert alert-danger">  {{ error }} </p>
  {% endif %}

  <form action="{% url 'users:signup' %}" method='POST' >
    {% csrf_token %}

    {{ form.as_p }}

    {% comment %} <div class="form-group">
      <input class="form-control" type="text" placeholder="username" name="username" required="true" />
    </div>

    <div class="form-group">
      <input class="form-control" type="password" placeholder="Password" name="password" required="true" />
    </div>

    <div class="form-group">
      <input class="form-control" 
        type="password" 
        placeholder="Password Confirmation" 
        name="password_confirmation" 
        required="true" 
      />
    </div>

    <div class="form-group">
      <input class="form-control" type="text" placeholder="first name" name="first_name" required="true" />
    </div>

    <div class="form-group">
      <input class="form-control" type="text" placeholder="Last name" name="last_name" required="true" />
    </div>

    <div class="form-group">
      <input class="form-control" type="email" placeholder="Eamil address" name="email" required="true" />
    </div> {% endcomment %}

    <button type="submit" class="btn btn-primary btn-block mt-5"> Register</button>
  </form>
  
{% endblock container %}

templates/users/update_profile.html
{% extends "base.html" %} 

{% load static %} 

{% block head_content %} 
  {% comment %} este user lo tomo de un middleware de authenticationMiddleware al autenticarme {% endcomment %}
  <title>@{{ request.user.username }} | Update profiles</title>
{% endblock %} 

{% block container %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 p-4" id="profile-box">
      <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {% comment %} {% if form.errors %}
          <p class="alert alert-danger"> {{ form.errors }} </p>
        {% endif %} {% endcomment %}


        <div class="media">

          {% if profile.picture %}
            <img
              src="{{ profile.picture.url }}"
              class="rounded-circle"
              height="50"
            />
          {% else %}
            <img
              src="{% static 'img/default-profile.png' %}"
              class="rounded-circle"
              height="50"
            />
          {% endif %}

          <div class="media-body">
            <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
            <p class="ml-4">
              <input type="file" name="picture" />
            </p>
          </div>
        </div>

        {% for error in form.picture.errors %}
          <div class="alert alert-danger">
            <b> Picture: </b> {{ error }}
          </div>
        {% endfor %}

        <hr />
        <br />

        {# commentiario: Manejar el Error y si hay error inserto una clase tambien voy a mostrar el valor ingresado que produjo el error #}
        <div class="form-group">
          <label>Website</label>
          <input
            class="form-control {% if form.website.errors %} is-invalid {% endif %}"
            type="text"
            name="website"
            placeholder="Website"
            value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
          />

          <div class="invalid-feedback">
            {% for error in form.website.errors  %}
              {{ error }}
            {% endfor %}
          </div>
        </div>

        {% comment %} Se encuentra asi de pegado para que no haya espacios de mas al renderizar el textarea {% endcomment %}
        <div class="form-group">
          <label>Biography</label>
          <textarea 
            class="form-control {% if form.biography.errors %} is-invalid {% endif %}"
            name="biography"
          >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}"</textarea>

          <div class="invalid-feedback">
            {% for error in form.biography.errors  %}
              {{ error }}
            {% endfor %}
          </div>
        </div>

        <div class="form-group">
          <label>Phone number</label>
          <input
            class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
            type="text"
            name="phone_number"
            placeholder="Phone number"
            value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
          />

          <div class="invalid-feedback">
            {% for error in form.phone_number.errors  %}
              {{ error }}
            {% endfor %}
          </div>

        </div>

        <button type="submit" class="btn btn-primary btn-block mt-5">
          Update info
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}